name: fuzzy
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - contourpy
      - cycler
      - fonttools
      - gensim
      - kiwisolver
      - matplotlib
      - networkx
      - numpy
      - packaging
      - pillow
      - pyparsing
      - python-dateutil
      - scikit-fuzzy
      - scipy
      - six
      - smart-open
      - tqdm
      - wrapt
